### ISSUE TITLE
Bị lỗi khi get list data

### ISSUE THREAD

**Issue by VanCanh96** [trieunho/FAH_TD#37]
- Sử dụng method FAHQuery.GetDataObject(dataSnapshot, new Post()) để get listData
- Tình hình là dòng Object item = snapshot.getValue(typeObject.getClass()); bị lỗi
- Nhờ anh ấy fix dùm
Note: Ko up hình đc

**Comment by trieunho** [comment]
Data trong firebase sai, check trước khi insert, delete
